# Dockerfile.main
FROM python:3.12-slim

WORKDIR /app

# Dépendances système
RUN apt-get update && apt-get install -y \
    git \
    ffmpeg \
    curl \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Environnement virtuel (léger)
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Dépendances Python
COPY requirement_3.12.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirement_3.12.txt

# Code source
COPY . .

# S'assurer que le script de démarrage est exécutable
RUN chmod +x init_main.sh

# Port exposé pour l'API Go → Python
EXPOSE 8000

# Démarrage par défaut
CMD ["./init_main.sh"]
