# Étape 1 : Compilation
FROM golang:1.22-alpine AS builder

# Répertoire de travail pour la compilation
WORKDIR /app

# Copier les fichiers du projet Go
COPY . .

# Téléchargement des dépendances
RUN go mod download

# Compilation du binaire Go
RUN go build -o main .

# Étape 2 : Image finale minimaliste
FROM alpine:latest

# Définir le répertoire de travail final
WORKDIR /app

# Copier le binaire depuis l'étape de build
COPY --from=builder /app/main ./main

# Exposer le port du serveur
EXPOSE 8080

# Démarrer l'application Go
CMD ["./main"]
