# Étape 1 : Compilation
FROM golang:1.22-alpine AS builder

# Répertoire de travail pour la compilation
WORKDIR /app

# Copier d'abord les fichiers de dépendances
COPY go.mod go.sum ./
RUN go mod download

# Copier le reste des fichiers
COPY . .

# Compilation du binaire Go
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/main.go

# Étape 2 : Image finale minimaliste
FROM alpine:latest

# Définir le répertoire de travail final
WORKDIR /app

# Copier le binaire depuis l'étape de build
COPY --from=builder /app/main ./main

# Exposer le port du serveur
EXPOSE 8080

# Démarrer l'application Go
CMD ["./main"]
